/**
 * File generated by Magnet rest2mobile 1.1 - Jun 17, 2015 8:22:02 PM
 * @see {@link http://developer.magnet.com}
 */

package com.magnetapi.examples.model.beans;


/**
 * Generated from json example
{
  "text" : "33.1mi",
  "value" : "53242"
}

 */

public class Distance {

  
  private String text;

  
  private String value;

  public String getText() {
    return text;
  }
  public String getValue() {
    return value;
  }

  /**
  * Builder for Distance
  **/
  public static class DistanceBuilder {
    private Distance toBuild = new Distance();

    public DistanceBuilder() {
    }

    public Distance build() {
      return toBuild;
    }

    public DistanceBuilder text(String value) {
      toBuild.text = value;
      return this;
    }
    public DistanceBuilder value(String value) {
      toBuild.value = value;
      return this;
    }
  }
}
