/**
 * File generated by Magnet rest2mobile 1.1 - Jun 17, 2015 8:22:02 PM
 * @see {@link http://developer.magnet.com}
 */

package com.magnetapi.examples.model.beans;


/**
 * Generated from json example
{
  "text" : "42mins",
  "value" : "2512"
}

 */

public class Duration {

  
  private String text;

  
  private String value;

  public String getText() {
    return text;
  }
  public String getValue() {
    return value;
  }

  /**
  * Builder for Duration
  **/
  public static class DurationBuilder {
    private Duration toBuild = new Duration();

    public DurationBuilder() {
    }

    public Duration build() {
      return toBuild;
    }

    public DurationBuilder text(String value) {
      toBuild.text = value;
      return this;
    }
    public DurationBuilder value(String value) {
      toBuild.value = value;
      return this;
    }
  }
}
