/**
 * File generated by Magnet rest2mobile 1.1 - Jun 17, 2015 8:22:02 PM
 * @see {@link http://developer.magnet.com}
 */

package com.magnetapi.examples.model.beans;

import java.util.List;

/**
 * Generated from json example
{
  "elements" : [ {
    "distance" : {
      "text" : "33.1mi",
      "value" : "53242"
    },
    "duration" : {
      "text" : "42mins",
      "value" : "2512"
    },
    "status" : "OK"
  } ]
}

 */

public class Row {

  
  private List<Element> elements;

  public List<Element> getElements() {
    return elements;
  }

  /**
  * Builder for Row
  **/
  public static class RowBuilder {
    private Row toBuild = new Row();

    public RowBuilder() {
    }

    public Row build() {
      return toBuild;
    }

    public RowBuilder elements(List<Element> value) {
      toBuild.elements = value;
      return this;
    }
  }
}
