/**
 * File generated by Magnet rest2mobile 1.1 - Jun 17, 2015 8:20:29 PM
 * @see {@link http://developer.magnet.com}
 */

package com.radoman.masinac.controller.api;

import com.magnet.android.mms.async.Call;
import com.magnet.android.mms.async.StateChangedListener;

import com.radoman.masinac.model.beans.*;

public interface Pavle {

  /**
   * Generated from URL GET http://ferometal.rs/parserPost.php?id=29&t=131
   * GET parserPost.php
   * @param id  style:QUERY
   * @param t  style:QUERY
   * @param listener
   * @return PavleLinkResult
   */
  Call<PavleLinkResult> pavleLink(
     String id,
     String t,
     StateChangedListener listener
  );


}
