/**
 * File generated by Magnet rest2mobile 1.1 - Jun 17, 2015 8:20:29 PM
 * @see {@link http://developer.magnet.com}
 */

package com.radoman.masinac.controller.api;

import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.controller.ControllerFactory;
import com.magnet.android.mms.controller.AbstractControllerSchemaFactory;
import com.magnet.android.mms.controller.RequestSchema;
import com.magnet.android.mms.controller.RequestSchema.JMethod;
import com.magnet.android.mms.controller.RequestSchema.JMeta;
import com.magnet.android.mms.controller.RequestSchema.JParam;

import java.util.Arrays;
import java.util.Collection;

import com.radoman.masinac.model.beans.*;

public class PavleFactory extends ControllerFactory<Pavle> {
  public PavleFactory(MagnetMobileClient magnetClient) {
    super(Pavle.class, PavleSchemaFactory.getInstance().getSchema(), magnetClient);
  }

  // Schema factory for controller Pavle
  public static class PavleSchemaFactory extends AbstractControllerSchemaFactory {
    private static PavleSchemaFactory __instance;

    public static synchronized PavleSchemaFactory getInstance() {
      if(null == __instance) {
        __instance = new PavleSchemaFactory();
      }

      return __instance;
    }

    private PavleSchemaFactory() {}

    protected synchronized void initSchemaMaps() {
      if(null != schema) {
        return;
      }

      schema = new RequestSchema();
      schema.setRootPath("");

      //controller schema for controller method pavleLink
      JMethod method1 = addMethod("pavleLink",
        "parserPost.php",
        "GET",
        PavleLinkResult.class,
        null,
        null,
        Arrays.asList("application/json"));
      method1.setBaseUrl("http://ferometal.rs");
      method1.addParam("id",
        "QUERY",
        String.class,
        null,
        "",
        true);
      method1.addParam("t",
        "QUERY",
        String.class,
        null,
        "",
        true);
    }

  }

}
