/**
 * File generated by Magnet rest2mobile 1.1 - Jun 17, 2015 8:20:29 PM
 * @see {@link http://developer.magnet.com}
 */

package com.radoman.masinac.model.beans;


/**
 * Generated from json example
{
  "naziv" : "Elektrotehnika_2015_azurno.pdf",
  "link" : "./download/file.php?id=1295&amp;sid=dd981e0ae284de0650bb529b006b3ecb"
}

 */

public class Attachment {

  
  private String link;

  
  private String naziv;

  public String getLink() {
    return link;
  }
  public String getNaziv() {
    return naziv;
  }

  /**
  * Builder for Attachment
  **/
  public static class AttachmentBuilder {
    private Attachment toBuild = new Attachment();

    public AttachmentBuilder() {
    }

    public Attachment build() {
      return toBuild;
    }

    public AttachmentBuilder link(String value) {
      toBuild.link = value;
      return this;
    }
    public AttachmentBuilder naziv(String value) {
      toBuild.naziv = value;
      return this;
    }
  }
}
