/**
 * File generated by Magnet rest2mobile 1.1 - Jun 17, 2015 8:20:29 PM
 * @see {@link http://developer.magnet.com}
 */

package com.radoman.masinac.model.beans;

import java.util.List;

/**
 * Generated from json example
{
  "naslov" : "Обавештењаза�?тудентеIV�?мене(Т.Стојић)",
  "content" : "Овдеће�?еналазитиобaвештењаза�?тудентеIV�?мене.ПредавањаивежбедржидоцентдрТоми�?лавСтојић.",
  "attachments" : [ ]
}

 */

public class Teme {

  
  private List<Attachment> attachments;

  
  private String content;

  
  private String naslov;

  public List<Attachment> getAttachments() {
    return attachments;
  }
  public String getContent() {
    return content;
  }
  public String getNaslov() {
    return naslov;
  }

  /**
  * Builder for Teme
  **/
  public static class TemeBuilder {
    private Teme toBuild = new Teme();

    public TemeBuilder() {
    }

    public Teme build() {
      return toBuild;
    }

    public TemeBuilder attachments(List<Attachment> value) {
      toBuild.attachments = value;
      return this;
    }
    public TemeBuilder content(String value) {
      toBuild.content = value;
      return this;
    }
    public TemeBuilder naslov(String value) {
      toBuild.naslov = value;
      return this;
    }
  }
}
