/**
 * File generated by Magnet rest2mobile 1.1 - Jun 17, 2015 8:22:52 PM
 * @see {@link http://developer.magnet.com}
 */

package com.magnetapi.examples.controller.api;

import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.controller.ControllerFactory;
import com.magnet.android.mms.controller.AbstractControllerSchemaFactory;
import com.magnet.android.mms.controller.RequestSchema;
import com.magnet.android.mms.controller.RequestSchema.JMethod;
import com.magnet.android.mms.controller.RequestSchema.JMeta;
import com.magnet.android.mms.controller.RequestSchema.JParam;

import java.util.Arrays;
import java.util.Collection;

import com.magnetapi.examples.model.beans.*;

public class ParserTemeFactory extends ControllerFactory<ParserTeme> {
  public ParserTemeFactory(MagnetMobileClient magnetClient) {
    super(ParserTeme.class, ParserTemeSchemaFactory.getInstance().getSchema(), magnetClient);
  }

  // Schema factory for controller ParserTeme
  public static class ParserTemeSchemaFactory extends AbstractControllerSchemaFactory {
    private static ParserTemeSchemaFactory __instance;

    public static synchronized ParserTemeSchemaFactory getInstance() {
      if(null == __instance) {
        __instance = new ParserTemeSchemaFactory();
      }

      return __instance;
    }

    private ParserTemeSchemaFactory() {}

    protected synchronized void initSchemaMaps() {
      if(null != schema) {
        return;
      }

      schema = new RequestSchema();
      schema.setRootPath("");

      //controller schema for controller method parserTeme
      JMethod method1 = addMethod("parserTeme",
        "parserPost.php",
        "GET",
        ParserTemeResult.class,
        null,
        null,
        Arrays.asList("application/json"));
      method1.setBaseUrl("http://ferometal.rs");
      method1.addParam("id",
        "QUERY",
        String.class,
        null,
        "",
        true);
      method1.addParam("t",
        "QUERY",
        String.class,
        null,
        "",
        true);
    }

  }

}
