/**
 * File generated by Magnet rest2mobile 1.1 - Jun 17, 2015 8:22:02 PM
 * @see {@link http://developer.magnet.com}
 */

package com.magnetapi.examples.controller.api;

import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.controller.ControllerFactory;
import com.magnet.android.mms.controller.AbstractControllerSchemaFactory;
import com.magnet.android.mms.controller.RequestSchema;
import com.magnet.android.mms.controller.RequestSchema.JMethod;
import com.magnet.android.mms.controller.RequestSchema.JMeta;
import com.magnet.android.mms.controller.RequestSchema.JParam;

import java.util.Arrays;
import java.util.Collection;

import com.magnetapi.examples.model.beans.*;

public class GoogleDistanceFactory extends ControllerFactory<GoogleDistance> {
  public GoogleDistanceFactory(MagnetMobileClient magnetClient) {
    super(GoogleDistance.class, GoogleDistanceSchemaFactory.getInstance().getSchema(), magnetClient);
  }

  // Schema factory for controller GoogleDistance
  public static class GoogleDistanceSchemaFactory extends AbstractControllerSchemaFactory {
    private static GoogleDistanceSchemaFactory __instance;

    public static synchronized GoogleDistanceSchemaFactory getInstance() {
      if(null == __instance) {
        __instance = new GoogleDistanceSchemaFactory();
      }

      return __instance;
    }

    private GoogleDistanceSchemaFactory() {}

    protected synchronized void initSchemaMaps() {
      if(null != schema) {
        return;
      }

      schema = new RequestSchema();
      schema.setRootPath("");

      //controller schema for controller method googleDistance
      JMethod method1 = addMethod("googleDistance",
        "maps/api/distancematrix/json",
        "GET",
        GoogleDistanceResult.class,
        null,
        null,
        Arrays.asList("application/json"));
      method1.setBaseUrl("http://maps.googleapis.com");
      method1.addParam("origins",
        "QUERY",
        String.class,
        null,
        "",
        true);
      method1.addParam("destinations",
        "QUERY",
        String.class,
        null,
        "",
        true);
      method1.addParam("sensor",
        "QUERY",
        String.class,
        null,
        "",
        true);
      method1.addParam("mode",
        "QUERY",
        String.class,
        null,
        "",
        true);
      method1.addParam("language",
        "QUERY",
        String.class,
        null,
        "",
        true);
      method1.addParam("units",
        "QUERY",
        String.class,
        null,
        "",
        true);
    }

  }

}
