/**
 * File generated by Magnet rest2mobile 1.1 - Jun 17, 2015 8:22:02 PM
 * @see {@link http://developer.magnet.com}
 */

package com.magnetapi.examples.controller.api;

import com.magnet.android.mms.async.Call;
import com.magnet.android.mms.async.StateChangedListener;

import com.magnetapi.examples.model.beans.*;

public interface GoogleDistance {

  /**
   * Generated from URL GET http://maps.googleapis.com/maps/api/distancematrix/json?origins=435+Tasso+Street+Palo+Alto+CA&destinations=Embarcadero+Street+San+Francisco+CA&sensor=false&mode=driving&language=en&units=imperial
   * GET maps/api/distancematrix/json
   * @param origins  style:QUERY
   * @param destinations  style:QUERY
   * @param sensor  style:QUERY
   * @param mode  style:QUERY
   * @param language  style:QUERY
   * @param units  style:QUERY
   * @param listener
   * @return GoogleDistanceResult
   */
  Call<GoogleDistanceResult> googleDistance(
     String origins,
     String destinations,
     String sensor,
     String mode,
     String language,
     String units,
     StateChangedListener listener
  );


}
